/*
2022년 1월의 도서 판매 데이터를 기준
저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 
저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력

 저자 ID를 오름차순으로,
 카테고리를 내림차순 정렬
*/
SELECT
    AU.AUTHOR_ID,
    AU.AUTHOR_NAME,
    BK.CATEGORY,
    SUM(BS.SALES * BK.PRICE) AS TOTALPRICE
FROM BOOK_SALES BS
LEFT JOIN BOOK BK
ON BS.BOOK_ID = BK.BOOK_ID
LEFT JOIN AUTHOR AU
ON BK.AUTHOR_ID = AU.AUTHOR_ID
WHERE MONTH(BS.SALES_DATE) = 1 AND YEAR(BS.SALES_DATE) = 2022
GROUP BY 1,2,3
ORDER BY AU.AUTHOR_ID ASC, BK.CATEGORY DESC;

